baseURL = 'http://onlyhy.github.io/'
title = 'ONLYHY'
theme = "hugo-coder"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
paginate = 20

publishDir = "docs"

enableRobotsTXT = true
enableEmoji = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

